name: Security CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  secrets:
    name: Secret Scanning
    uses: thiagoolima99/repo-central/.github/workflows/reusable-gitleaks.yml@main
    secrets: inherit
    permissions:
      contents: read
